name: Frontend Unit Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Appy/Appy-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install frontend dependencies
        run: npm install

      - name: Run frontend unit tests
        run: npx ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
